action_id: trunk-single-player-auto-upgrade
date: 2024-09-11 11:23:51
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1726053831
full_timestamp:
  nanos: 898642000
  seconds: 1726053831
trunk_version: 1.22.5
