action_id: trunk-single-player-auto-upgrade
date: 2024-09-12 11:23:52
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1726140232
full_timestamp:
  nanos: 107743000
  seconds: 1726140232
trunk_version: 1.22.5
