@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\HP\AppData\Local\trunk\tools\osv-scanner\1.8.5-57ed0affcdab32e4a86c03cdc994ee79;C:\Users\HP\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\HP\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
