@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\HP\AppData\Local\trunk\tools\trufflehog\3.81.10-800087f2477b4010f9038e060abcfa8e;C:\Users\HP\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\HP\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
