@echo off
REM Generated by trunk tool 'yamllint'
set PYTHONUTF8=1
set PATH=C:\Users\HP\AppData\Local\trunk\tools\yamllint\1.35.1-e7d6fa4aa0e9fc42a0c29c9b3ec55e5e/bin;C:\Users\HP\AppData\Local\trunk\tools\yamllint\1.35.1-e7d6fa4aa0e9fc42a0c29c9b3ec55e5e/Scripts;C:\Users\HP\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\HP\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\HP\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\HP\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set VIRTUAL_ENV=C:\Users\HP\AppData\Local\trunk\tools\yamllint\1.35.1-e7d6fa4aa0e9fc42a0c29c9b3ec55e5e

start /w /b yamllint %*
