action_id: trunk-upgrade-available
date: 2024-09-07 18:39:15
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: .trunk/trunk.yaml
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1725734355
full_timestamp:
  nanos: 656701000
  seconds: 1725734355
trunk_version: 1.22.5
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
