action_id: trunk-upgrade-available
date: 2024-09-11 10:29:12
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: .trunk/trunk.yaml
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1726050552
full_timestamp:
  nanos: 644627000
  seconds: 1726050552
trunk_version: 1.22.5
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
