action_id: trunk-share-with-everyone
date: 2024-09-11 14:38:53
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1726065533
full_timestamp:
  nanos: 449216000
  seconds: 1726065533
trunk_version: 1.22.5
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
