action_id: trunk-share-with-everyone
date: 2024-09-12 10:23:51
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1726136631
full_timestamp:
  nanos: 233678000
  seconds: 1726136631
trunk_version: 1.22.5
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
